### ISSUE TITLE
[Obsolete] Mondo meta-grouping classes

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3661]
Hi, The following terms below are proposed obsoletion candidates in Mondo. These are meta grouping classes that are under the top level 'disease or disorder' term, and upon discussion on the Mondo curation calls, it seems these are not clinically relevant and are difficult to maintain, so we propose obsoleting these terms in a future release (on or after December 2021).

| Mondo ID             |        Label                                              |        proposed obsoletion   date |
|----------------------|-----------------------------------------------------------|--------------------------|
|        MONDO:0021194 |              disease by subcellular system affected       |        12/1/21           |
| MONDO:0021195        |         disease by cellular process disrupted             |         12/01/21          |
| MONDO:0021196        |         disease by molecular activity disrupted           |         12/01/21          |
| MONDO:0021197        |         disease by cellular component affected            |         12/01/21           |
| MONDO:0021199        |         disease by anatomical system                      |         12/01/21          |
| MONDO:0024505        |         disorder by anatomical region                     |         12/01/21          |
| MONDO:0044969        |         disease of membrane bound organelle               |        12/01/21         |
| MONDO:0044971        |         disease of macromolecular complex                 |         12/01/21          |
| MONDO:0044974        |         disease of supramolecular complex                 |        12/01/21         |
| MONDO:0044975        |         disease of transporter activity                   |         12/01/21         |
| MONDO:0044976        | disease   of catalytic activity                           | 12/01/21                 |
| MONDO:0044977        | disease   of receptor activity                            | 12/01/21                  |
| MONDO:0044979        | disease   by cell type                                    | 12/01/21                  |
| MONDO:0044980        |         disease of signal transduction                    |         12/01/21         |
| MONDO:0000839 | congenital abnormality | 12/01/21

**Comment by nicolevasilevsky** [comment]
added obsoletion tags in PR https://github.com/monarch-initiative/mondo/pull/3662

**Comment by nicolevasilevsky** [comment]
- [ ] MONDO:0021194 | disease by subcellular system affected | 12/1/21
- [ ] MONDO:0021195 | disease by cellular process disrupted | 12/01/21
- [ ] MONDO:0021196 | disease by molecular activity disrupted | 12/01/21
- [ ] MONDO:0021197 | disease by cellular component affected | 12/01/21
- [ ] MONDO:0021199 | disease by anatomical system | 12/01/21
- [ ] MONDO:0024505 | disorder by anatomical region | 12/01/21
- [ ] MONDO:0044969 | disease of membrane bound organelle | 12/01/21
- [ ] MONDO:0044971 | disease of macromolecular complex | 12/01/21
- [ ] MONDO:0044974 | disease of supramolecular complex | 12/01/21
- [ ] MONDO:0044975 | disease of transporter activity | 12/01/21
- [ ] MONDO:0044976 | disease of catalytic activity | 12/01/21
- [ ] MONDO:0044977 | disease of receptor activity | 12/01/21
- [ ] MONDO:0044979 | disease by cell type | 12/01/21
- [ ] MONDO:0044980 | disease of signal transduction | 12/01/21
- [ ] MONDO:0000839 | congenital abnormality | 12/01/21
