### ISSUE TITLE
OMIM genes pipeline issues - Superticket

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo#8317]
Parent ticket to handle issues from testing the OMIM pipeline: https://github.com/monarch-initiative/mondo/pull/8108

- [x] Gene association representation in `omim.ttl` https://github.com/monarch-initiative/omim/issues/156 (@joeflack4)
This is the initial fix for Sabrina's finding that the OMIM pipeline PR (3) Genes should not be added if the OMIM record is associated with multiple genes. 
- [x] Create gold standard list of diseases from OMIM that have disease defining genes  https://github.com/monarch-initiative/omim/issues/161
- [x] Fix incorrect multiple gene associations currently in Mondo https://github.com/monarch-initiative/mondo/issues/8276
- [x] Fix mismatch of gene symbols used in EquivalentTo and SubClassOf statements https://github.com/monarch-initiative/mondo/issues/8275
- [x] Fix OMIM pipeline to keep gene annotations with sources from clinicalgenome, PMID, and orcid https://github.com/monarch-initiative/mondo/pull/8108
- [x] Add qc check to flag any case where there is >1 affected gene https://github.com/monarch-initiative/mondo/issues/8316
- [x] Add qc check so that a Mondo term does not have both a germline and somatic gene association https://github.com/monarch-initiative/mondo/issues/8443
As part of this, mark any curator agreed upon multiple associations as excluded from this qc check

**Comment by twhetzel** [comment]
All subtasks are now done!
